/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeReportRouteImport } from './routes/time-report'
import { Route as TeamPerformanceRouteImport } from './routes/team-performance'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SystemDocsRouteImport } from './routes/system-docs'
import { Route as SomusIaRouteImport } from './routes/somus-ia'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesPerformanceRouteImport } from './routes/sales-performance'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistrationsRouteImport } from './routes/registrations'
import { Route as ProjectsOverviewRouteImport } from './routes/projects-overview'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as PortalClienteRouteImport } from './routes/portal-cliente'
import { Route as PasswordsRouteImport } from './routes/passwords'
import { Route as OperacoesRouteImport } from './routes/operacoes'
import { Route as MissoesRouteImport } from './routes/missoes'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeTrailRouteImport } from './routes/knowledge-trail'
import { Route as IntelligentCentralRouteImport } from './routes/intelligent-central'
import { Route as InfoCenterRouteImport } from './routes/info-center'
import { Route as GamificacaoRouteImport } from './routes/gamificacao'
import { Route as FinancialDashboardRouteImport } from './routes/financial-dashboard'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as CollaboratorsRouteImport } from './routes/collaborators'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BriefingsRouteImport } from './routes/briefings'
import { Route as BolaoRouteImport } from './routes/bolao'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SomusIaIndexRouteImport } from './routes/somus-ia.index'
import { Route as RegistrationsIndexRouteImport } from './routes/registrations.index'
import { Route as OperacoesIndexRouteImport } from './routes/operacoes.index'
import { Route as GamificacaoIndexRouteImport } from './routes/gamificacao.index'
import { Route as FinanceiroIndexRouteImport } from './routes/financeiro.index'
import { Route as ContractsIndexRouteImport } from './routes/contracts.index'
import { Route as ComercialIndexRouteImport } from './routes/comercial.index'
import { Route as AlcateiaIndexRouteImport } from './routes/alcateia.index'
import { Route as SomusIaAgentesRouteImport } from './routes/somus-ia.agentes'
import { Route as SomusIaConversationIdRouteImport } from './routes/somus-ia.$conversationId'
import { Route as RegistrationsIdRouteImport } from './routes/registrations.$id'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as OperacoesSenhasRouteImport } from './routes/operacoes.senhas'
import { Route as OperacoesProjetosRouteImport } from './routes/operacoes.projetos'
import { Route as OperacoesPerformanceRouteImport } from './routes/operacoes.performance'
import { Route as OperacoesModelosRouteImport } from './routes/operacoes.modelos'
import { Route as OperacoesFormulariosRouteImport } from './routes/operacoes.formularios'
import { Route as OnboardingTokenRouteImport } from './routes/onboarding.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as GamificacaoResgatesRouteImport } from './routes/gamificacao.resgates'
import { Route as GamificacaoPinsRouteImport } from './routes/gamificacao.pins'
import { Route as GamificacaoMissoesRouteImport } from './routes/gamificacao.missoes'
import { Route as GamificacaoLojaRouteImport } from './routes/gamificacao.loja'
import { Route as GamificacaoHabitosRouteImport } from './routes/gamificacao.habitos'
import { Route as GamificacaoGaleriaDoLoboRouteImport } from './routes/gamificacao.galeria-do-lobo'
import { Route as GamificacaoEstrelaDoLiderRouteImport } from './routes/gamificacao.estrela-do-lider'
import { Route as FinanceiroIndicadoresRouteImport } from './routes/financeiro.indicadores'
import { Route as FDataRouteImport } from './routes/f.$data'
import { Route as CronogramaTokenRouteImport } from './routes/cronograma.$token'
import { Route as ContratoTokenRouteImport } from './routes/contrato.$token'
import { Route as ContractsContractIdRouteImport } from './routes/contracts.$contractId'
import { Route as ComercialProspeccoesRouteImport } from './routes/comercial.prospeccoes'
import { Route as ComercialMetasRouteImport } from './routes/comercial.metas'
import { Route as ComercialFunilRouteImport } from './routes/comercial.funil'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ClienteMetasRouteImport } from './routes/cliente.metas'
import { Route as ClienteGlossarioRouteImport } from './routes/cliente.glossario'
import { Route as ClienteAgentesRouteImport } from './routes/cliente.agentes'
import { Route as BriefingTokenRouteImport } from './routes/briefing.$token'
import { Route as AtasAtaIdRouteImport } from './routes/atas.$ataId'
import { Route as AlcateiaPlaylistRouteImport } from './routes/alcateia.playlist'
import { Route as ClienteTrilhasIndexRouteImport } from './routes/cliente.trilhas.index'
import { Route as PAtaAtaIdRouteImport } from './routes/p.ata.$ataId'
import { Route as ClienteTrilhasTrackIdRouteImport } from './routes/cliente.trilhas.$trackId'
import { Route as ClientesClienteIdProjetosProjetoIdRouteImport } from './routes/clientes.$clienteId.projetos.$projetoId'
import { Route as ClientesClienteIdProjetosProjetoIdAtasAtaIdRouteImport } from './routes/clientes.$clienteId.projetos.$projetoId.atas.$ataId'

const TimeReportRoute = TimeReportRouteImport.update({
  id: '/time-report',
  path: '/time-report',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamPerformanceRoute = TeamPerformanceRouteImport.update({
  id: '/team-performance',
  path: '/team-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemDocsRoute = SystemDocsRouteImport.update({
  id: '/system-docs',
  path: '/system-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const SomusIaRoute = SomusIaRouteImport.update({
  id: '/somus-ia',
  path: '/somus-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesPerformanceRoute = SalesPerformanceRouteImport.update({
  id: '/sales-performance',
  path: '/sales-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationsRoute = RegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsOverviewRoute = ProjectsOverviewRouteImport.update({
  id: '/projects-overview',
  path: '/projects-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalClienteRoute = PortalClienteRouteImport.update({
  id: '/portal-cliente',
  path: '/portal-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordsRoute = PasswordsRouteImport.update({
  id: '/passwords',
  path: '/passwords',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesRoute = OperacoesRouteImport.update({
  id: '/operacoes',
  path: '/operacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MissoesRoute = MissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeTrailRoute = KnowledgeTrailRouteImport.update({
  id: '/knowledge-trail',
  path: '/knowledge-trail',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligentCentralRoute = IntelligentCentralRouteImport.update({
  id: '/intelligent-central',
  path: '/intelligent-central',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoCenterRoute = InfoCenterRouteImport.update({
  id: '/info-center',
  path: '/info-center',
  getParentRoute: () => rootRouteImport,
} as any)
const GamificacaoRoute = GamificacaoRouteImport.update({
  id: '/gamificacao',
  path: '/gamificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialDashboardRoute = FinancialDashboardRouteImport.update({
  id: '/financial-dashboard',
  path: '/financial-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaboratorsRoute = CollaboratorsRouteImport.update({
  id: '/collaborators',
  path: '/collaborators',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsRoute = BriefingsRouteImport.update({
  id: '/briefings',
  path: '/briefings',
  getParentRoute: () => rootRouteImport,
} as any)
const BolaoRoute = BolaoRouteImport.update({
  id: '/bolao',
  path: '/bolao',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SomusIaIndexRoute = SomusIaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SomusIaRoute,
} as any)
const RegistrationsIndexRoute = RegistrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegistrationsRoute,
} as any)
const OperacoesIndexRoute = OperacoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperacoesRoute,
} as any)
const GamificacaoIndexRoute = GamificacaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamificacaoRoute,
} as any)
const FinanceiroIndexRoute = FinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceiroRoute,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialIndexRoute = ComercialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComercialRoute,
} as any)
const AlcateiaIndexRoute = AlcateiaIndexRouteImport.update({
  id: '/alcateia/',
  path: '/alcateia/',
  getParentRoute: () => rootRouteImport,
} as any)
const SomusIaAgentesRoute = SomusIaAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => SomusIaRoute,
} as any)
const SomusIaConversationIdRoute = SomusIaConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => SomusIaRoute,
} as any)
const RegistrationsIdRoute = RegistrationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RegistrationsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const OperacoesSenhasRoute = OperacoesSenhasRouteImport.update({
  id: '/senhas',
  path: '/senhas',
  getParentRoute: () => OperacoesRoute,
} as any)
const OperacoesProjetosRoute = OperacoesProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => OperacoesRoute,
} as any)
const OperacoesPerformanceRoute = OperacoesPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => OperacoesRoute,
} as any)
const OperacoesModelosRoute = OperacoesModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => OperacoesRoute,
} as any)
const OperacoesFormulariosRoute = OperacoesFormulariosRouteImport.update({
  id: '/formularios',
  path: '/formularios',
  getParentRoute: () => OperacoesRoute,
} as any)
const OnboardingTokenRoute = OnboardingTokenRouteImport.update({
  id: '/onboarding/$token',
  path: '/onboarding/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GamificacaoResgatesRoute = GamificacaoResgatesRouteImport.update({
  id: '/resgates',
  path: '/resgates',
  getParentRoute: () => GamificacaoRoute,
} as any)
const GamificacaoPinsRoute = GamificacaoPinsRouteImport.update({
  id: '/pins',
  path: '/pins',
  getParentRoute: () => GamificacaoRoute,
} as any)
const GamificacaoMissoesRoute = GamificacaoMissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => GamificacaoRoute,
} as any)
const GamificacaoLojaRoute = GamificacaoLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => GamificacaoRoute,
} as any)
const GamificacaoHabitosRoute = GamificacaoHabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => GamificacaoRoute,
} as any)
const GamificacaoGaleriaDoLoboRoute =
  GamificacaoGaleriaDoLoboRouteImport.update({
    id: '/galeria-do-lobo',
    path: '/galeria-do-lobo',
    getParentRoute: () => GamificacaoRoute,
  } as any)
const GamificacaoEstrelaDoLiderRoute =
  GamificacaoEstrelaDoLiderRouteImport.update({
    id: '/estrela-do-lider',
    path: '/estrela-do-lider',
    getParentRoute: () => GamificacaoRoute,
  } as any)
const FinanceiroIndicadoresRoute = FinanceiroIndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FDataRoute = FDataRouteImport.update({
  id: '/f/$data',
  path: '/f/$data',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramaTokenRoute = CronogramaTokenRouteImport.update({
  id: '/cronograma/$token',
  path: '/cronograma/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratoTokenRoute = ContratoTokenRouteImport.update({
  id: '/contrato/$token',
  path: '/contrato/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsContractIdRoute = ContractsContractIdRouteImport.update({
  id: '/contracts/$contractId',
  path: '/contracts/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialProspeccoesRoute = ComercialProspeccoesRouteImport.update({
  id: '/prospeccoes',
  path: '/prospeccoes',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialMetasRoute = ComercialMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialFunilRoute = ComercialFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => ComercialRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const ClienteMetasRoute = ClienteMetasRouteImport.update({
  id: '/cliente/metas',
  path: '/cliente/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteGlossarioRoute = ClienteGlossarioRouteImport.update({
  id: '/cliente/glossario',
  path: '/cliente/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteAgentesRoute = ClienteAgentesRouteImport.update({
  id: '/cliente/agentes',
  path: '/cliente/agentes',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingTokenRoute = BriefingTokenRouteImport.update({
  id: '/briefing/$token',
  path: '/briefing/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AtasAtaIdRoute = AtasAtaIdRouteImport.update({
  id: '/atas/$ataId',
  path: '/atas/$ataId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlcateiaPlaylistRoute = AlcateiaPlaylistRouteImport.update({
  id: '/alcateia/playlist',
  path: '/alcateia/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteTrilhasIndexRoute = ClienteTrilhasIndexRouteImport.update({
  id: '/cliente/trilhas/',
  path: '/cliente/trilhas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PAtaAtaIdRoute = PAtaAtaIdRouteImport.update({
  id: '/p/ata/$ataId',
  path: '/p/ata/$ataId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteTrilhasTrackIdRoute = ClienteTrilhasTrackIdRouteImport.update({
  id: '/cliente/trilhas/$trackId',
  path: '/cliente/trilhas/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClienteIdProjetosProjetoIdRoute =
  ClientesClienteIdProjetosProjetoIdRouteImport.update({
    id: '/clientes/$clienteId/projetos/$projetoId',
    path: '/clientes/$clienteId/projetos/$projetoId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientesClienteIdProjetosProjetoIdAtasAtaIdRoute =
  ClientesClienteIdProjetosProjetoIdAtasAtaIdRouteImport.update({
    id: '/atas/$ataId',
    path: '/atas/$ataId',
    getParentRoute: () => ClientesClienteIdProjetosProjetoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/bolao': typeof BolaoRoute
  '/briefings': typeof BriefingsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/collaborators': typeof CollaboratorsRoute
  '/comercial': typeof ComercialRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/financial-dashboard': typeof FinancialDashboardRoute
  '/gamificacao': typeof GamificacaoRouteWithChildren
  '/info-center': typeof InfoCenterRoute
  '/intelligent-central': typeof IntelligentCentralRoute
  '/knowledge-trail': typeof KnowledgeTrailRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/missoes': typeof MissoesRoute
  '/operacoes': typeof OperacoesRouteWithChildren
  '/passwords': typeof PasswordsRoute
  '/portal-cliente': typeof PortalClienteRoute
  '/processes': typeof ProcessesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects-overview': typeof ProjectsOverviewRoute
  '/registrations': typeof RegistrationsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sales-performance': typeof SalesPerformanceRoute
  '/settings': typeof SettingsRoute
  '/somus-ia': typeof SomusIaRouteWithChildren
  '/system-docs': typeof SystemDocsRoute
  '/tasks': typeof TasksRoute
  '/team-performance': typeof TeamPerformanceRoute
  '/time-report': typeof TimeReportRoute
  '/alcateia/playlist': typeof AlcateiaPlaylistRoute
  '/atas/$ataId': typeof AtasAtaIdRoute
  '/briefing/$token': typeof BriefingTokenRoute
  '/cliente/agentes': typeof ClienteAgentesRoute
  '/cliente/glossario': typeof ClienteGlossarioRoute
  '/cliente/metas': typeof ClienteMetasRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/comercial/funil': typeof ComercialFunilRoute
  '/comercial/metas': typeof ComercialMetasRoute
  '/comercial/prospeccoes': typeof ComercialProspeccoesRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/contrato/$token': typeof ContratoTokenRoute
  '/cronograma/$token': typeof CronogramaTokenRoute
  '/f/$data': typeof FDataRoute
  '/financeiro/indicadores': typeof FinanceiroIndicadoresRoute
  '/gamificacao/estrela-do-lider': typeof GamificacaoEstrelaDoLiderRoute
  '/gamificacao/galeria-do-lobo': typeof GamificacaoGaleriaDoLoboRoute
  '/gamificacao/habitos': typeof GamificacaoHabitosRoute
  '/gamificacao/loja': typeof GamificacaoLojaRoute
  '/gamificacao/missoes': typeof GamificacaoMissoesRoute
  '/gamificacao/pins': typeof GamificacaoPinsRoute
  '/gamificacao/resgates': typeof GamificacaoResgatesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/$token': typeof OnboardingTokenRoute
  '/operacoes/formularios': typeof OperacoesFormulariosRoute
  '/operacoes/modelos': typeof OperacoesModelosRoute
  '/operacoes/performance': typeof OperacoesPerformanceRoute
  '/operacoes/projetos': typeof OperacoesProjetosRoute
  '/operacoes/senhas': typeof OperacoesSenhasRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/registrations/$id': typeof RegistrationsIdRoute
  '/somus-ia/$conversationId': typeof SomusIaConversationIdRoute
  '/somus-ia/agentes': typeof SomusIaAgentesRoute
  '/alcateia/': typeof AlcateiaIndexRoute
  '/comercial/': typeof ComercialIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/gamificacao/': typeof GamificacaoIndexRoute
  '/operacoes/': typeof OperacoesIndexRoute
  '/registrations/': typeof RegistrationsIndexRoute
  '/somus-ia/': typeof SomusIaIndexRoute
  '/cliente/trilhas/$trackId': typeof ClienteTrilhasTrackIdRoute
  '/p/ata/$ataId': typeof PAtaAtaIdRoute
  '/cliente/trilhas/': typeof ClienteTrilhasIndexRoute
  '/clientes/$clienteId/projetos/$projetoId': typeof ClientesClienteIdProjetosProjetoIdRouteWithChildren
  '/clientes/$clienteId/projetos/$projetoId/atas/$ataId': typeof ClientesClienteIdProjetosProjetoIdAtasAtaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/bolao': typeof BolaoRoute
  '/briefings': typeof BriefingsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/collaborators': typeof CollaboratorsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/financial-dashboard': typeof FinancialDashboardRoute
  '/info-center': typeof InfoCenterRoute
  '/intelligent-central': typeof IntelligentCentralRoute
  '/knowledge-trail': typeof KnowledgeTrailRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/missoes': typeof MissoesRoute
  '/passwords': typeof PasswordsRoute
  '/portal-cliente': typeof PortalClienteRoute
  '/processes': typeof ProcessesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects-overview': typeof ProjectsOverviewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales-performance': typeof SalesPerformanceRoute
  '/settings': typeof SettingsRoute
  '/system-docs': typeof SystemDocsRoute
  '/tasks': typeof TasksRoute
  '/team-performance': typeof TeamPerformanceRoute
  '/time-report': typeof TimeReportRoute
  '/alcateia/playlist': typeof AlcateiaPlaylistRoute
  '/atas/$ataId': typeof AtasAtaIdRoute
  '/briefing/$token': typeof BriefingTokenRoute
  '/cliente/agentes': typeof ClienteAgentesRoute
  '/cliente/glossario': typeof ClienteGlossarioRoute
  '/cliente/metas': typeof ClienteMetasRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/comercial/funil': typeof ComercialFunilRoute
  '/comercial/metas': typeof ComercialMetasRoute
  '/comercial/prospeccoes': typeof ComercialProspeccoesRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/contrato/$token': typeof ContratoTokenRoute
  '/cronograma/$token': typeof CronogramaTokenRoute
  '/f/$data': typeof FDataRoute
  '/financeiro/indicadores': typeof FinanceiroIndicadoresRoute
  '/gamificacao/estrela-do-lider': typeof GamificacaoEstrelaDoLiderRoute
  '/gamificacao/galeria-do-lobo': typeof GamificacaoGaleriaDoLoboRoute
  '/gamificacao/habitos': typeof GamificacaoHabitosRoute
  '/gamificacao/loja': typeof GamificacaoLojaRoute
  '/gamificacao/missoes': typeof GamificacaoMissoesRoute
  '/gamificacao/pins': typeof GamificacaoPinsRoute
  '/gamificacao/resgates': typeof GamificacaoResgatesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/$token': typeof OnboardingTokenRoute
  '/operacoes/formularios': typeof OperacoesFormulariosRoute
  '/operacoes/modelos': typeof OperacoesModelosRoute
  '/operacoes/performance': typeof OperacoesPerformanceRoute
  '/operacoes/projetos': typeof OperacoesProjetosRoute
  '/operacoes/senhas': typeof OperacoesSenhasRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/registrations/$id': typeof RegistrationsIdRoute
  '/somus-ia/$conversationId': typeof SomusIaConversationIdRoute
  '/somus-ia/agentes': typeof SomusIaAgentesRoute
  '/alcateia': typeof AlcateiaIndexRoute
  '/comercial': typeof ComercialIndexRoute
  '/contracts': typeof ContractsIndexRoute
  '/financeiro': typeof FinanceiroIndexRoute
  '/gamificacao': typeof GamificacaoIndexRoute
  '/operacoes': typeof OperacoesIndexRoute
  '/registrations': typeof RegistrationsIndexRoute
  '/somus-ia': typeof SomusIaIndexRoute
  '/cliente/trilhas/$trackId': typeof ClienteTrilhasTrackIdRoute
  '/p/ata/$ataId': typeof PAtaAtaIdRoute
  '/cliente/trilhas': typeof ClienteTrilhasIndexRoute
  '/clientes/$clienteId/projetos/$projetoId': typeof ClientesClienteIdProjetosProjetoIdRouteWithChildren
  '/clientes/$clienteId/projetos/$projetoId/atas/$ataId': typeof ClientesClienteIdProjetosProjetoIdAtasAtaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/bolao': typeof BolaoRoute
  '/briefings': typeof BriefingsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/collaborators': typeof CollaboratorsRoute
  '/comercial': typeof ComercialRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/financial-dashboard': typeof FinancialDashboardRoute
  '/gamificacao': typeof GamificacaoRouteWithChildren
  '/info-center': typeof InfoCenterRoute
  '/intelligent-central': typeof IntelligentCentralRoute
  '/knowledge-trail': typeof KnowledgeTrailRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/missoes': typeof MissoesRoute
  '/operacoes': typeof OperacoesRouteWithChildren
  '/passwords': typeof PasswordsRoute
  '/portal-cliente': typeof PortalClienteRoute
  '/processes': typeof ProcessesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects-overview': typeof ProjectsOverviewRoute
  '/registrations': typeof RegistrationsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sales-performance': typeof SalesPerformanceRoute
  '/settings': typeof SettingsRoute
  '/somus-ia': typeof SomusIaRouteWithChildren
  '/system-docs': typeof SystemDocsRoute
  '/tasks': typeof TasksRoute
  '/team-performance': typeof TeamPerformanceRoute
  '/time-report': typeof TimeReportRoute
  '/alcateia/playlist': typeof AlcateiaPlaylistRoute
  '/atas/$ataId': typeof AtasAtaIdRoute
  '/briefing/$token': typeof BriefingTokenRoute
  '/cliente/agentes': typeof ClienteAgentesRoute
  '/cliente/glossario': typeof ClienteGlossarioRoute
  '/cliente/metas': typeof ClienteMetasRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/comercial/funil': typeof ComercialFunilRoute
  '/comercial/metas': typeof ComercialMetasRoute
  '/comercial/prospeccoes': typeof ComercialProspeccoesRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/contrato/$token': typeof ContratoTokenRoute
  '/cronograma/$token': typeof CronogramaTokenRoute
  '/f/$data': typeof FDataRoute
  '/financeiro/indicadores': typeof FinanceiroIndicadoresRoute
  '/gamificacao/estrela-do-lider': typeof GamificacaoEstrelaDoLiderRoute
  '/gamificacao/galeria-do-lobo': typeof GamificacaoGaleriaDoLoboRoute
  '/gamificacao/habitos': typeof GamificacaoHabitosRoute
  '/gamificacao/loja': typeof GamificacaoLojaRoute
  '/gamificacao/missoes': typeof GamificacaoMissoesRoute
  '/gamificacao/pins': typeof GamificacaoPinsRoute
  '/gamificacao/resgates': typeof GamificacaoResgatesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/$token': typeof OnboardingTokenRoute
  '/operacoes/formularios': typeof OperacoesFormulariosRoute
  '/operacoes/modelos': typeof OperacoesModelosRoute
  '/operacoes/performance': typeof OperacoesPerformanceRoute
  '/operacoes/projetos': typeof OperacoesProjetosRoute
  '/operacoes/senhas': typeof OperacoesSenhasRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/registrations/$id': typeof RegistrationsIdRoute
  '/somus-ia/$conversationId': typeof SomusIaConversationIdRoute
  '/somus-ia/agentes': typeof SomusIaAgentesRoute
  '/alcateia/': typeof AlcateiaIndexRoute
  '/comercial/': typeof ComercialIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/gamificacao/': typeof GamificacaoIndexRoute
  '/operacoes/': typeof OperacoesIndexRoute
  '/registrations/': typeof RegistrationsIndexRoute
  '/somus-ia/': typeof SomusIaIndexRoute
  '/cliente/trilhas/$trackId': typeof ClienteTrilhasTrackIdRoute
  '/p/ata/$ataId': typeof PAtaAtaIdRoute
  '/cliente/trilhas/': typeof ClienteTrilhasIndexRoute
  '/clientes/$clienteId/projetos/$projetoId': typeof ClientesClienteIdProjetosProjetoIdRouteWithChildren
  '/clientes/$clienteId/projetos/$projetoId/atas/$ataId': typeof ClientesClienteIdProjetosProjetoIdAtasAtaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/bolao'
    | '/briefings'
    | '/clients'
    | '/collaborators'
    | '/comercial'
    | '/dashboard'
    | '/documents'
    | '/financeiro'
    | '/financial-dashboard'
    | '/gamificacao'
    | '/info-center'
    | '/intelligent-central'
    | '/knowledge-trail'
    | '/login'
    | '/meetings'
    | '/missoes'
    | '/operacoes'
    | '/passwords'
    | '/portal-cliente'
    | '/processes'
    | '/projects'
    | '/projects-overview'
    | '/registrations'
    | '/reset-password'
    | '/sales-performance'
    | '/settings'
    | '/somus-ia'
    | '/system-docs'
    | '/tasks'
    | '/team-performance'
    | '/time-report'
    | '/alcateia/playlist'
    | '/atas/$ataId'
    | '/briefing/$token'
    | '/cliente/agentes'
    | '/cliente/glossario'
    | '/cliente/metas'
    | '/clients/$clientId'
    | '/comercial/funil'
    | '/comercial/metas'
    | '/comercial/prospeccoes'
    | '/contracts/$contractId'
    | '/contrato/$token'
    | '/cronograma/$token'
    | '/f/$data'
    | '/financeiro/indicadores'
    | '/gamificacao/estrela-do-lider'
    | '/gamificacao/galeria-do-lobo'
    | '/gamificacao/habitos'
    | '/gamificacao/loja'
    | '/gamificacao/missoes'
    | '/gamificacao/pins'
    | '/gamificacao/resgates'
    | '/invite/$token'
    | '/onboarding/$token'
    | '/operacoes/formularios'
    | '/operacoes/modelos'
    | '/operacoes/performance'
    | '/operacoes/projetos'
    | '/operacoes/senhas'
    | '/projects/$projectId'
    | '/registrations/$id'
    | '/somus-ia/$conversationId'
    | '/somus-ia/agentes'
    | '/alcateia/'
    | '/comercial/'
    | '/contracts/'
    | '/financeiro/'
    | '/gamificacao/'
    | '/operacoes/'
    | '/registrations/'
    | '/somus-ia/'
    | '/cliente/trilhas/$trackId'
    | '/p/ata/$ataId'
    | '/cliente/trilhas/'
    | '/clientes/$clienteId/projetos/$projetoId'
    | '/clientes/$clienteId/projetos/$projetoId/atas/$ataId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/bolao'
    | '/briefings'
    | '/clients'
    | '/collaborators'
    | '/dashboard'
    | '/documents'
    | '/financial-dashboard'
    | '/info-center'
    | '/intelligent-central'
    | '/knowledge-trail'
    | '/login'
    | '/meetings'
    | '/missoes'
    | '/passwords'
    | '/portal-cliente'
    | '/processes'
    | '/projects'
    | '/projects-overview'
    | '/reset-password'
    | '/sales-performance'
    | '/settings'
    | '/system-docs'
    | '/tasks'
    | '/team-performance'
    | '/time-report'
    | '/alcateia/playlist'
    | '/atas/$ataId'
    | '/briefing/$token'
    | '/cliente/agentes'
    | '/cliente/glossario'
    | '/cliente/metas'
    | '/clients/$clientId'
    | '/comercial/funil'
    | '/comercial/metas'
    | '/comercial/prospeccoes'
    | '/contracts/$contractId'
    | '/contrato/$token'
    | '/cronograma/$token'
    | '/f/$data'
    | '/financeiro/indicadores'
    | '/gamificacao/estrela-do-lider'
    | '/gamificacao/galeria-do-lobo'
    | '/gamificacao/habitos'
    | '/gamificacao/loja'
    | '/gamificacao/missoes'
    | '/gamificacao/pins'
    | '/gamificacao/resgates'
    | '/invite/$token'
    | '/onboarding/$token'
    | '/operacoes/formularios'
    | '/operacoes/modelos'
    | '/operacoes/performance'
    | '/operacoes/projetos'
    | '/operacoes/senhas'
    | '/projects/$projectId'
    | '/registrations/$id'
    | '/somus-ia/$conversationId'
    | '/somus-ia/agentes'
    | '/alcateia'
    | '/comercial'
    | '/contracts'
    | '/financeiro'
    | '/gamificacao'
    | '/operacoes'
    | '/registrations'
    | '/somus-ia'
    | '/cliente/trilhas/$trackId'
    | '/p/ata/$ataId'
    | '/cliente/trilhas'
    | '/clientes/$clienteId/projetos/$projetoId'
    | '/clientes/$clienteId/projetos/$projetoId/atas/$ataId'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/bolao'
    | '/briefings'
    | '/clients'
    | '/collaborators'
    | '/comercial'
    | '/dashboard'
    | '/documents'
    | '/financeiro'
    | '/financial-dashboard'
    | '/gamificacao'
    | '/info-center'
    | '/intelligent-central'
    | '/knowledge-trail'
    | '/login'
    | '/meetings'
    | '/missoes'
    | '/operacoes'
    | '/passwords'
    | '/portal-cliente'
    | '/processes'
    | '/projects'
    | '/projects-overview'
    | '/registrations'
    | '/reset-password'
    | '/sales-performance'
    | '/settings'
    | '/somus-ia'
    | '/system-docs'
    | '/tasks'
    | '/team-performance'
    | '/time-report'
    | '/alcateia/playlist'
    | '/atas/$ataId'
    | '/briefing/$token'
    | '/cliente/agentes'
    | '/cliente/glossario'
    | '/cliente/metas'
    | '/clients/$clientId'
    | '/comercial/funil'
    | '/comercial/metas'
    | '/comercial/prospeccoes'
    | '/contracts/$contractId'
    | '/contrato/$token'
    | '/cronograma/$token'
    | '/f/$data'
    | '/financeiro/indicadores'
    | '/gamificacao/estrela-do-lider'
    | '/gamificacao/galeria-do-lobo'
    | '/gamificacao/habitos'
    | '/gamificacao/loja'
    | '/gamificacao/missoes'
    | '/gamificacao/pins'
    | '/gamificacao/resgates'
    | '/invite/$token'
    | '/onboarding/$token'
    | '/operacoes/formularios'
    | '/operacoes/modelos'
    | '/operacoes/performance'
    | '/operacoes/projetos'
    | '/operacoes/senhas'
    | '/projects/$projectId'
    | '/registrations/$id'
    | '/somus-ia/$conversationId'
    | '/somus-ia/agentes'
    | '/alcateia/'
    | '/comercial/'
    | '/contracts/'
    | '/financeiro/'
    | '/gamificacao/'
    | '/operacoes/'
    | '/registrations/'
    | '/somus-ia/'
    | '/cliente/trilhas/$trackId'
    | '/p/ata/$ataId'
    | '/cliente/trilhas/'
    | '/clientes/$clienteId/projetos/$projetoId'
    | '/clientes/$clienteId/projetos/$projetoId/atas/$ataId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  BolaoRoute: typeof BolaoRoute
  BriefingsRoute: typeof BriefingsRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  CollaboratorsRoute: typeof CollaboratorsRoute
  ComercialRoute: typeof ComercialRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  FinancialDashboardRoute: typeof FinancialDashboardRoute
  GamificacaoRoute: typeof GamificacaoRouteWithChildren
  InfoCenterRoute: typeof InfoCenterRoute
  IntelligentCentralRoute: typeof IntelligentCentralRoute
  KnowledgeTrailRoute: typeof KnowledgeTrailRoute
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRoute
  MissoesRoute: typeof MissoesRoute
  OperacoesRoute: typeof OperacoesRouteWithChildren
  PasswordsRoute: typeof PasswordsRoute
  PortalClienteRoute: typeof PortalClienteRoute
  ProcessesRoute: typeof ProcessesRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ProjectsOverviewRoute: typeof ProjectsOverviewRoute
  RegistrationsRoute: typeof RegistrationsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalesPerformanceRoute: typeof SalesPerformanceRoute
  SettingsRoute: typeof SettingsRoute
  SomusIaRoute: typeof SomusIaRouteWithChildren
  SystemDocsRoute: typeof SystemDocsRoute
  TasksRoute: typeof TasksRoute
  TeamPerformanceRoute: typeof TeamPerformanceRoute
  TimeReportRoute: typeof TimeReportRoute
  AlcateiaPlaylistRoute: typeof AlcateiaPlaylistRoute
  AtasAtaIdRoute: typeof AtasAtaIdRoute
  BriefingTokenRoute: typeof BriefingTokenRoute
  ClienteAgentesRoute: typeof ClienteAgentesRoute
  ClienteGlossarioRoute: typeof ClienteGlossarioRoute
  ClienteMetasRoute: typeof ClienteMetasRoute
  ContractsContractIdRoute: typeof ContractsContractIdRoute
  ContratoTokenRoute: typeof ContratoTokenRoute
  CronogramaTokenRoute: typeof CronogramaTokenRoute
  FDataRoute: typeof FDataRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OnboardingTokenRoute: typeof OnboardingTokenRoute
  AlcateiaIndexRoute: typeof AlcateiaIndexRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
  ClienteTrilhasTrackIdRoute: typeof ClienteTrilhasTrackIdRoute
  PAtaAtaIdRoute: typeof PAtaAtaIdRoute
  ClienteTrilhasIndexRoute: typeof ClienteTrilhasIndexRoute
  ClientesClienteIdProjetosProjetoIdRoute: typeof ClientesClienteIdProjetosProjetoIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/time-report': {
      id: '/time-report'
      path: '/time-report'
      fullPath: '/time-report'
      preLoaderRoute: typeof TimeReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-performance': {
      id: '/team-performance'
      path: '/team-performance'
      fullPath: '/team-performance'
      preLoaderRoute: typeof TeamPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-docs': {
      id: '/system-docs'
      path: '/system-docs'
      fullPath: '/system-docs'
      preLoaderRoute: typeof SystemDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/somus-ia': {
      id: '/somus-ia'
      path: '/somus-ia'
      fullPath: '/somus-ia'
      preLoaderRoute: typeof SomusIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-performance': {
      id: '/sales-performance'
      path: '/sales-performance'
      fullPath: '/sales-performance'
      preLoaderRoute: typeof SalesPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrations': {
      id: '/registrations'
      path: '/registrations'
      fullPath: '/registrations'
      preLoaderRoute: typeof RegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects-overview': {
      id: '/projects-overview'
      path: '/projects-overview'
      fullPath: '/projects-overview'
      preLoaderRoute: typeof ProjectsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-cliente': {
      id: '/portal-cliente'
      path: '/portal-cliente'
      fullPath: '/portal-cliente'
      preLoaderRoute: typeof PortalClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwords': {
      id: '/passwords'
      path: '/passwords'
      fullPath: '/passwords'
      preLoaderRoute: typeof PasswordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes': {
      id: '/operacoes'
      path: '/operacoes'
      fullPath: '/operacoes'
      preLoaderRoute: typeof OperacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missoes': {
      id: '/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof MissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-trail': {
      id: '/knowledge-trail'
      path: '/knowledge-trail'
      fullPath: '/knowledge-trail'
      preLoaderRoute: typeof KnowledgeTrailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligent-central': {
      id: '/intelligent-central'
      path: '/intelligent-central'
      fullPath: '/intelligent-central'
      preLoaderRoute: typeof IntelligentCentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info-center': {
      id: '/info-center'
      path: '/info-center'
      fullPath: '/info-center'
      preLoaderRoute: typeof InfoCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamificacao': {
      id: '/gamificacao'
      path: '/gamificacao'
      fullPath: '/gamificacao'
      preLoaderRoute: typeof GamificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-dashboard': {
      id: '/financial-dashboard'
      path: '/financial-dashboard'
      fullPath: '/financial-dashboard'
      preLoaderRoute: typeof FinancialDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborators': {
      id: '/collaborators'
      path: '/collaborators'
      fullPath: '/collaborators'
      preLoaderRoute: typeof CollaboratorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings': {
      id: '/briefings'
      path: '/briefings'
      fullPath: '/briefings'
      preLoaderRoute: typeof BriefingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolao': {
      id: '/bolao'
      path: '/bolao'
      fullPath: '/bolao'
      preLoaderRoute: typeof BolaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/somus-ia/': {
      id: '/somus-ia/'
      path: '/'
      fullPath: '/somus-ia/'
      preLoaderRoute: typeof SomusIaIndexRouteImport
      parentRoute: typeof SomusIaRoute
    }
    '/registrations/': {
      id: '/registrations/'
      path: '/'
      fullPath: '/registrations/'
      preLoaderRoute: typeof RegistrationsIndexRouteImport
      parentRoute: typeof RegistrationsRoute
    }
    '/operacoes/': {
      id: '/operacoes/'
      path: '/'
      fullPath: '/operacoes/'
      preLoaderRoute: typeof OperacoesIndexRouteImport
      parentRoute: typeof OperacoesRoute
    }
    '/gamificacao/': {
      id: '/gamificacao/'
      path: '/'
      fullPath: '/gamificacao/'
      preLoaderRoute: typeof GamificacaoIndexRouteImport
      parentRoute: typeof GamificacaoRoute
    }
    '/financeiro/': {
      id: '/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof FinanceiroIndexRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/': {
      id: '/comercial/'
      path: '/'
      fullPath: '/comercial/'
      preLoaderRoute: typeof ComercialIndexRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/alcateia/': {
      id: '/alcateia/'
      path: '/alcateia'
      fullPath: '/alcateia/'
      preLoaderRoute: typeof AlcateiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/somus-ia/agentes': {
      id: '/somus-ia/agentes'
      path: '/agentes'
      fullPath: '/somus-ia/agentes'
      preLoaderRoute: typeof SomusIaAgentesRouteImport
      parentRoute: typeof SomusIaRoute
    }
    '/somus-ia/$conversationId': {
      id: '/somus-ia/$conversationId'
      path: '/$conversationId'
      fullPath: '/somus-ia/$conversationId'
      preLoaderRoute: typeof SomusIaConversationIdRouteImport
      parentRoute: typeof SomusIaRoute
    }
    '/registrations/$id': {
      id: '/registrations/$id'
      path: '/$id'
      fullPath: '/registrations/$id'
      preLoaderRoute: typeof RegistrationsIdRouteImport
      parentRoute: typeof RegistrationsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/operacoes/senhas': {
      id: '/operacoes/senhas'
      path: '/senhas'
      fullPath: '/operacoes/senhas'
      preLoaderRoute: typeof OperacoesSenhasRouteImport
      parentRoute: typeof OperacoesRoute
    }
    '/operacoes/projetos': {
      id: '/operacoes/projetos'
      path: '/projetos'
      fullPath: '/operacoes/projetos'
      preLoaderRoute: typeof OperacoesProjetosRouteImport
      parentRoute: typeof OperacoesRoute
    }
    '/operacoes/performance': {
      id: '/operacoes/performance'
      path: '/performance'
      fullPath: '/operacoes/performance'
      preLoaderRoute: typeof OperacoesPerformanceRouteImport
      parentRoute: typeof OperacoesRoute
    }
    '/operacoes/modelos': {
      id: '/operacoes/modelos'
      path: '/modelos'
      fullPath: '/operacoes/modelos'
      preLoaderRoute: typeof OperacoesModelosRouteImport
      parentRoute: typeof OperacoesRoute
    }
    '/operacoes/formularios': {
      id: '/operacoes/formularios'
      path: '/formularios'
      fullPath: '/operacoes/formularios'
      preLoaderRoute: typeof OperacoesFormulariosRouteImport
      parentRoute: typeof OperacoesRoute
    }
    '/onboarding/$token': {
      id: '/onboarding/$token'
      path: '/onboarding/$token'
      fullPath: '/onboarding/$token'
      preLoaderRoute: typeof OnboardingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamificacao/resgates': {
      id: '/gamificacao/resgates'
      path: '/resgates'
      fullPath: '/gamificacao/resgates'
      preLoaderRoute: typeof GamificacaoResgatesRouteImport
      parentRoute: typeof GamificacaoRoute
    }
    '/gamificacao/pins': {
      id: '/gamificacao/pins'
      path: '/pins'
      fullPath: '/gamificacao/pins'
      preLoaderRoute: typeof GamificacaoPinsRouteImport
      parentRoute: typeof GamificacaoRoute
    }
    '/gamificacao/missoes': {
      id: '/gamificacao/missoes'
      path: '/missoes'
      fullPath: '/gamificacao/missoes'
      preLoaderRoute: typeof GamificacaoMissoesRouteImport
      parentRoute: typeof GamificacaoRoute
    }
    '/gamificacao/loja': {
      id: '/gamificacao/loja'
      path: '/loja'
      fullPath: '/gamificacao/loja'
      preLoaderRoute: typeof GamificacaoLojaRouteImport
      parentRoute: typeof GamificacaoRoute
    }
    '/gamificacao/habitos': {
      id: '/gamificacao/habitos'
      path: '/habitos'
      fullPath: '/gamificacao/habitos'
      preLoaderRoute: typeof GamificacaoHabitosRouteImport
      parentRoute: typeof GamificacaoRoute
    }
    '/gamificacao/galeria-do-lobo': {
      id: '/gamificacao/galeria-do-lobo'
      path: '/galeria-do-lobo'
      fullPath: '/gamificacao/galeria-do-lobo'
      preLoaderRoute: typeof GamificacaoGaleriaDoLoboRouteImport
      parentRoute: typeof GamificacaoRoute
    }
    '/gamificacao/estrela-do-lider': {
      id: '/gamificacao/estrela-do-lider'
      path: '/estrela-do-lider'
      fullPath: '/gamificacao/estrela-do-lider'
      preLoaderRoute: typeof GamificacaoEstrelaDoLiderRouteImport
      parentRoute: typeof GamificacaoRoute
    }
    '/financeiro/indicadores': {
      id: '/financeiro/indicadores'
      path: '/indicadores'
      fullPath: '/financeiro/indicadores'
      preLoaderRoute: typeof FinanceiroIndicadoresRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/f/$data': {
      id: '/f/$data'
      path: '/f/$data'
      fullPath: '/f/$data'
      preLoaderRoute: typeof FDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronograma/$token': {
      id: '/cronograma/$token'
      path: '/cronograma/$token'
      fullPath: '/cronograma/$token'
      preLoaderRoute: typeof CronogramaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrato/$token': {
      id: '/contrato/$token'
      path: '/contrato/$token'
      fullPath: '/contrato/$token'
      preLoaderRoute: typeof ContratoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$contractId': {
      id: '/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof ContractsContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/prospeccoes': {
      id: '/comercial/prospeccoes'
      path: '/prospeccoes'
      fullPath: '/comercial/prospeccoes'
      preLoaderRoute: typeof ComercialProspeccoesRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/comercial/metas': {
      id: '/comercial/metas'
      path: '/metas'
      fullPath: '/comercial/metas'
      preLoaderRoute: typeof ComercialMetasRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/comercial/funil': {
      id: '/comercial/funil'
      path: '/funil'
      fullPath: '/comercial/funil'
      preLoaderRoute: typeof ComercialFunilRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/cliente/metas': {
      id: '/cliente/metas'
      path: '/cliente/metas'
      fullPath: '/cliente/metas'
      preLoaderRoute: typeof ClienteMetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/glossario': {
      id: '/cliente/glossario'
      path: '/cliente/glossario'
      fullPath: '/cliente/glossario'
      preLoaderRoute: typeof ClienteGlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/agentes': {
      id: '/cliente/agentes'
      path: '/cliente/agentes'
      fullPath: '/cliente/agentes'
      preLoaderRoute: typeof ClienteAgentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing/$token': {
      id: '/briefing/$token'
      path: '/briefing/$token'
      fullPath: '/briefing/$token'
      preLoaderRoute: typeof BriefingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atas/$ataId': {
      id: '/atas/$ataId'
      path: '/atas/$ataId'
      fullPath: '/atas/$ataId'
      preLoaderRoute: typeof AtasAtaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alcateia/playlist': {
      id: '/alcateia/playlist'
      path: '/alcateia/playlist'
      fullPath: '/alcateia/playlist'
      preLoaderRoute: typeof AlcateiaPlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/trilhas/': {
      id: '/cliente/trilhas/'
      path: '/cliente/trilhas'
      fullPath: '/cliente/trilhas/'
      preLoaderRoute: typeof ClienteTrilhasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/ata/$ataId': {
      id: '/p/ata/$ataId'
      path: '/p/ata/$ataId'
      fullPath: '/p/ata/$ataId'
      preLoaderRoute: typeof PAtaAtaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/trilhas/$trackId': {
      id: '/cliente/trilhas/$trackId'
      path: '/cliente/trilhas/$trackId'
      fullPath: '/cliente/trilhas/$trackId'
      preLoaderRoute: typeof ClienteTrilhasTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clienteId/projetos/$projetoId': {
      id: '/clientes/$clienteId/projetos/$projetoId'
      path: '/clientes/$clienteId/projetos/$projetoId'
      fullPath: '/clientes/$clienteId/projetos/$projetoId'
      preLoaderRoute: typeof ClientesClienteIdProjetosProjetoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clienteId/projetos/$projetoId/atas/$ataId': {
      id: '/clientes/$clienteId/projetos/$projetoId/atas/$ataId'
      path: '/atas/$ataId'
      fullPath: '/clientes/$clienteId/projetos/$projetoId/atas/$ataId'
      preLoaderRoute: typeof ClientesClienteIdProjetosProjetoIdAtasAtaIdRouteImport
      parentRoute: typeof ClientesClienteIdProjetosProjetoIdRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface ComercialRouteChildren {
  ComercialFunilRoute: typeof ComercialFunilRoute
  ComercialMetasRoute: typeof ComercialMetasRoute
  ComercialProspeccoesRoute: typeof ComercialProspeccoesRoute
  ComercialIndexRoute: typeof ComercialIndexRoute
}

const ComercialRouteChildren: ComercialRouteChildren = {
  ComercialFunilRoute: ComercialFunilRoute,
  ComercialMetasRoute: ComercialMetasRoute,
  ComercialProspeccoesRoute: ComercialProspeccoesRoute,
  ComercialIndexRoute: ComercialIndexRoute,
}

const ComercialRouteWithChildren = ComercialRoute._addFileChildren(
  ComercialRouteChildren,
)

interface FinanceiroRouteChildren {
  FinanceiroIndicadoresRoute: typeof FinanceiroIndicadoresRoute
  FinanceiroIndexRoute: typeof FinanceiroIndexRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroIndicadoresRoute: FinanceiroIndicadoresRoute,
  FinanceiroIndexRoute: FinanceiroIndexRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

interface GamificacaoRouteChildren {
  GamificacaoEstrelaDoLiderRoute: typeof GamificacaoEstrelaDoLiderRoute
  GamificacaoGaleriaDoLoboRoute: typeof GamificacaoGaleriaDoLoboRoute
  GamificacaoHabitosRoute: typeof GamificacaoHabitosRoute
  GamificacaoLojaRoute: typeof GamificacaoLojaRoute
  GamificacaoMissoesRoute: typeof GamificacaoMissoesRoute
  GamificacaoPinsRoute: typeof GamificacaoPinsRoute
  GamificacaoResgatesRoute: typeof GamificacaoResgatesRoute
  GamificacaoIndexRoute: typeof GamificacaoIndexRoute
}

const GamificacaoRouteChildren: GamificacaoRouteChildren = {
  GamificacaoEstrelaDoLiderRoute: GamificacaoEstrelaDoLiderRoute,
  GamificacaoGaleriaDoLoboRoute: GamificacaoGaleriaDoLoboRoute,
  GamificacaoHabitosRoute: GamificacaoHabitosRoute,
  GamificacaoLojaRoute: GamificacaoLojaRoute,
  GamificacaoMissoesRoute: GamificacaoMissoesRoute,
  GamificacaoPinsRoute: GamificacaoPinsRoute,
  GamificacaoResgatesRoute: GamificacaoResgatesRoute,
  GamificacaoIndexRoute: GamificacaoIndexRoute,
}

const GamificacaoRouteWithChildren = GamificacaoRoute._addFileChildren(
  GamificacaoRouteChildren,
)

interface OperacoesRouteChildren {
  OperacoesFormulariosRoute: typeof OperacoesFormulariosRoute
  OperacoesModelosRoute: typeof OperacoesModelosRoute
  OperacoesPerformanceRoute: typeof OperacoesPerformanceRoute
  OperacoesProjetosRoute: typeof OperacoesProjetosRoute
  OperacoesSenhasRoute: typeof OperacoesSenhasRoute
  OperacoesIndexRoute: typeof OperacoesIndexRoute
}

const OperacoesRouteChildren: OperacoesRouteChildren = {
  OperacoesFormulariosRoute: OperacoesFormulariosRoute,
  OperacoesModelosRoute: OperacoesModelosRoute,
  OperacoesPerformanceRoute: OperacoesPerformanceRoute,
  OperacoesProjetosRoute: OperacoesProjetosRoute,
  OperacoesSenhasRoute: OperacoesSenhasRoute,
  OperacoesIndexRoute: OperacoesIndexRoute,
}

const OperacoesRouteWithChildren = OperacoesRoute._addFileChildren(
  OperacoesRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface RegistrationsRouteChildren {
  RegistrationsIdRoute: typeof RegistrationsIdRoute
  RegistrationsIndexRoute: typeof RegistrationsIndexRoute
}

const RegistrationsRouteChildren: RegistrationsRouteChildren = {
  RegistrationsIdRoute: RegistrationsIdRoute,
  RegistrationsIndexRoute: RegistrationsIndexRoute,
}

const RegistrationsRouteWithChildren = RegistrationsRoute._addFileChildren(
  RegistrationsRouteChildren,
)

interface SomusIaRouteChildren {
  SomusIaConversationIdRoute: typeof SomusIaConversationIdRoute
  SomusIaAgentesRoute: typeof SomusIaAgentesRoute
  SomusIaIndexRoute: typeof SomusIaIndexRoute
}

const SomusIaRouteChildren: SomusIaRouteChildren = {
  SomusIaConversationIdRoute: SomusIaConversationIdRoute,
  SomusIaAgentesRoute: SomusIaAgentesRoute,
  SomusIaIndexRoute: SomusIaIndexRoute,
}

const SomusIaRouteWithChildren =
  SomusIaRoute._addFileChildren(SomusIaRouteChildren)

interface ClientesClienteIdProjetosProjetoIdRouteChildren {
  ClientesClienteIdProjetosProjetoIdAtasAtaIdRoute: typeof ClientesClienteIdProjetosProjetoIdAtasAtaIdRoute
}

const ClientesClienteIdProjetosProjetoIdRouteChildren: ClientesClienteIdProjetosProjetoIdRouteChildren =
  {
    ClientesClienteIdProjetosProjetoIdAtasAtaIdRoute:
      ClientesClienteIdProjetosProjetoIdAtasAtaIdRoute,
  }

const ClientesClienteIdProjetosProjetoIdRouteWithChildren =
  ClientesClienteIdProjetosProjetoIdRoute._addFileChildren(
    ClientesClienteIdProjetosProjetoIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  BolaoRoute: BolaoRoute,
  BriefingsRoute: BriefingsRoute,
  ClientsRoute: ClientsRouteWithChildren,
  CollaboratorsRoute: CollaboratorsRoute,
  ComercialRoute: ComercialRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  FinancialDashboardRoute: FinancialDashboardRoute,
  GamificacaoRoute: GamificacaoRouteWithChildren,
  InfoCenterRoute: InfoCenterRoute,
  IntelligentCentralRoute: IntelligentCentralRoute,
  KnowledgeTrailRoute: KnowledgeTrailRoute,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRoute,
  MissoesRoute: MissoesRoute,
  OperacoesRoute: OperacoesRouteWithChildren,
  PasswordsRoute: PasswordsRoute,
  PortalClienteRoute: PortalClienteRoute,
  ProcessesRoute: ProcessesRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ProjectsOverviewRoute: ProjectsOverviewRoute,
  RegistrationsRoute: RegistrationsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SalesPerformanceRoute: SalesPerformanceRoute,
  SettingsRoute: SettingsRoute,
  SomusIaRoute: SomusIaRouteWithChildren,
  SystemDocsRoute: SystemDocsRoute,
  TasksRoute: TasksRoute,
  TeamPerformanceRoute: TeamPerformanceRoute,
  TimeReportRoute: TimeReportRoute,
  AlcateiaPlaylistRoute: AlcateiaPlaylistRoute,
  AtasAtaIdRoute: AtasAtaIdRoute,
  BriefingTokenRoute: BriefingTokenRoute,
  ClienteAgentesRoute: ClienteAgentesRoute,
  ClienteGlossarioRoute: ClienteGlossarioRoute,
  ClienteMetasRoute: ClienteMetasRoute,
  ContractsContractIdRoute: ContractsContractIdRoute,
  ContratoTokenRoute: ContratoTokenRoute,
  CronogramaTokenRoute: CronogramaTokenRoute,
  FDataRoute: FDataRoute,
  InviteTokenRoute: InviteTokenRoute,
  OnboardingTokenRoute: OnboardingTokenRoute,
  AlcateiaIndexRoute: AlcateiaIndexRoute,
  ContractsIndexRoute: ContractsIndexRoute,
  ClienteTrilhasTrackIdRoute: ClienteTrilhasTrackIdRoute,
  PAtaAtaIdRoute: PAtaAtaIdRoute,
  ClienteTrilhasIndexRoute: ClienteTrilhasIndexRoute,
  ClientesClienteIdProjetosProjetoIdRoute:
    ClientesClienteIdProjetosProjetoIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
